version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:227541536114:task-definition/universe-backend:3"
        LoadBalancerInfo:
          ContainerName: "universe-backend"
          ContainerPort: 80
